# docker-compose is not used in this project, so you can ignore this file.

version: "3.8"
services:
  web:
    depends_on:
      - api
    build: ./web
    restart: unless-stopped
    ports:
      - 3000:3000
  api:
    depends_on:
      - db
    build: ./api
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      DB_HOST: db
      DB_PORT: 3306
    env_file:
      - .env
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - .env
    volumes:
      - crypteye:/var/lib/mysql
volumes:
  crypteye: